version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest

    working_directory: ~/laravel

    steps:
      - checkout

      #To be used in case of Browser Tests
      # - run: mkdir test-reports
      # - run:
      #     name: Download Selenium
      #     command: |
      #       curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium
      #     command: |
      #       java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true

      - run: sudo apt install -y libsqlite3-dev
      # - run: composer self-update
      - run: composer --version
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run

      # - run: sudo apt install -y libsqlite3-dev

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "composer.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run: composer install -n --prefer-dist

      # - save_cache:
      #     paths:
      #       - ./vendor
      #     key: v1-dependencies-{{ checksum "composer.json" }}

      # - run: touch storage/testing.sqlite
      # - run: php artisan migrate --env=testing --database=sqlite_testing --force
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run

      # - run: php artisan migrate:refresh --env=testing --force
      # - run: php artisan db:seed
      
      # run tests!
      - run: vendor/bin/phpunit
