version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest

    working_directory: ~/laravel

    steps:
      - checkout

      #To be used in case of Browser Tests
      # - run: mkdir test-reports
      # - run:
      #     name: Download Selenium
      #     command: |
      #       curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium
      #     command: |
      #       java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true

      - run: sudo apt install -y libsqlite3-dev
      - run: sudo apt install -y libsqlite3-0
      - run: composer --version
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force

      # run tests!
      - run: vendor/bin/phpunit
