version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
        environment:
          APP_ENV: testing
          APP_KEY: base64:D+c9WV2OBzUJMn5tftYqa+LwK1Pw9/h78jAq4ygBzPg=
          DB_DATABASE: circle_test
          DB_USERNAME: root
          # CACHE_DRIVER: redis
          # SESSION_DRIVER: redis
          SKIP_LONG_TESTS: true

      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=circle_test


    working_directory: ~/laravel

    steps:

      - checkout

      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql

      - run: composer --version
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: cp .env.circleci .env

      - run: php artisan migrate:refresh --seed --force --env=testing -vvv

      # run tests!
      - run: vendor/bin/phpunit
